version: "3"

services:
  db-mongodb:
    image: mongo:4.4.17-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    
volumes:
  mongodb-data: